server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/saas-export-100?characterEncoding=utf-8
    username: root
    password: root
  application:
    name: company-service

eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:9091/eureka
  instance:
    ip-address: 127.0.0.1 # ip地址
    prefer-ip-address: true # 更倾向于使用ip，而不是host名
    instance-id: ${eureka.instance.ip-address}:${server.port} # 自定义实例的id