server:
  port: 8082
spring:
  application:
    name: consumer-service
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:9091/eureka
  instance:
    ip-address: 127.0.0.1 # ip地址
    prefer-ip-address: true # 更倾向于使用ip，而不是host名
    instance-id: ${eureka.instance.ip-address}:${server.port} # 自定义实例的id
